services:
  web:
    build: .
    command: gunicorn OnlineJudgeProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SQLITE_PATH=/app/data/db.sqlite3

volumes:
  db_data:
