services:
  - type: web
    name: online-judge-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn OnlineJudgeProject.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: OnlineJudgeProject.settings
    plan: free
